version: 2.1

jobs:
  say-hello:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"

  setup-ngrok:
    docker:
      - image: ubuntu:20.04  # Ubuntu 20.04 uses "focal"
    environment:
      NGROK_AUTH_TOKEN: $NGROK_AUTH_TOKEN  # Set this in CircleCI project settings
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            apt-get update
            apt-get install -y curl jq sudo  # Fix 2: Added "sudo"
      - run:
          name: Add Ngrok Repository (Focal)
          command: |
            curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null
            # Fix 3: Changed "buster" to "focal" for Ubuntu 20.04
            echo "deb https://ngrok-agent.s3.amazonaws.com focal main" | sudo tee /etc/apt/sources.list.d/ngrok.list
      - run:
          name: Install Ngrok
          command: sudo apt-get update && sudo apt-get install -y ngrok
      - run:
          name: Authenticate Ngrok
          command: ngrok config add-authtoken "$NGROK_AUTH_TOKEN"
      - run:
          name: Test Ngrok
          command: ngrok --version

workflows:
  main-workflow:
    jobs:
      - say-hello
      - setup-ngrok  # Fix 4: Proper workflow structure