version: 2.1

jobs:
  say-hello:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"

  setup-ngrok:  # New job for Ngrok setup
    docker:
      - image: ubuntu:20.04
    environment:
      NGROK_AUTH_TOKEN: your_token_here  # Use CircleCI env var instead
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            apt-get update
            apt-get install -y curl jq
      - run:
          name: Add Ngrok Repository
          command: |
            curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null
            echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list
      - run:
          name: Install Ngrok
          command: apt-get update && apt-get install -y ngrok
      - run:
          name: Authenticate Ngrok
          command: ngrok config add-authtoken "$NGROK_AUTH_TOKEN"
      - run:
          name: Test Ngrok
          command: ngrok --version

workflows:
  main-workflow:
    jobs:
      - say-hello
      - setup-ngrok